version: "3"

services:
  project:
    container_name: project
    image: parking
    build: .
    depends_on:
      - db
      - redis
      - celery
    command: ./wait-for-it.sh db:5432 -- python3 manage.py runserver 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/project
    env_file:
      - .env

  db:
    image: postgres:10
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

  redis:
    image: redis:3.2
    volumes:
      - redis:/data

  celery:
    image: parking
    depends_on:
      - db
      - redis
    command: ./wait-for-it.sh db:5432 -- celery -A project worker -l info
    environment:
      C_FORCE_ROOT: "1"

volumes:
  db:
  redis: