version: "2"

services:
  project_img:
    build: .
    image: parking

  project_app:
    image: parking
    volumes:
      - .:/project
    env_file:
      - .env

  db:
    image: postgres:10
    volumes:
      - db:/var/lib/postgresql/data

  project:
    extends: project_app
    depends_on:
      - db
    command: ./wait-for-it.sh db:5432 -- python3 manage.py runserver 0:8000
    ports:
      - "8000:8000"

  packages:
    extends: project_app
    volumes:
      - .:/host

volumes:
  db:
  redis: