# Generated by Django 2.2 on 2020-02-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20200218_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='language_code',
            field=models.CharField(default='am', max_length=5),
        ),
    ]
