# Generated by Django 2.2 on 2020-02-13 19:42

import core.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20200211_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_message',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.utils.utils.get_file_path),
        ),
    ]
