# Generated by Django 2.2 on 2020-03-26 21:19

import core.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagetemplate_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.utils.get_file_path),
        ),
    ]
