---

app_root_dir: "/var/www/parking"
app_venv_dir: "{{ app_root_dir }}/venv"
app_log_dir: "{{ app_root_dir }}/log"
app_run_dir: "{{ app_root_dir }}/run"
app_repo_branch: "master"
app_url_scheme: "https"


deploy_group: deployers
ssh_dir: "/home/sipan/.ssh/"
ssh_key_name: "findy_key"