# Generated by Django 2.2 on 2020-03-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200312_1828'),
        ('core', '0002_auto_20200218_0824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
