# Generated by Django 2.2 on 2020-02-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200211_1756'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['car_number', 'user'], name='users_car_car_num_4d10eb_idx'),
        ),
    ]
