# Generated by Django 2.2 on 2020-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200212_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='currency',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_method',
            field=models.CharField(choices=[('sms', 'sms notification'), ('app', 'Application Notification'), ('bh', 'Both Types')], default='app', max_length=3),
        ),
    ]
