# Generated by Django 2.2 on 2020-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200212_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_phone_number',
            field=models.BooleanField(default=False),
        ),
    ]
