# Generated by Django 2.2 on 2020-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_car_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number_valid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='reset_password_valid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
